package fes.aragon.modelo;

public enum TipoError {
    PALABRAS,NUMEROS,RFC,CORREO,TELEFONO,FOLIO,TRABAJADOR,CLIENTE, MONTO, NOMBRE, APELLIDO, APELLIDOMATERNO, DOMICILIO, COLMUNDEM, CP, CIUDAD, ANOSRESIDENCIA, CURP, }
